spring:
  application:
    name: meeting-srv-eureka-client
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/meeting_db}
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/meeting_db}
    password: 123
    user: postgres
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true
    baseline-version: 0
    baseline-description: "init"
  config:
    import: ${CONFIG_URI:optional:configserver:http://localhost:8888/}
  rabbitmq:
    host: ${RABBIT_URI:localhost}
    port: 5672
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    #preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
websocket:
  url: ${USER_HOSTNAME:ws://localhost:9001/websocket-user}
application:
  constraints:
    secret-key: "aa641fed0dd8893053c23823e1295c4b605b39872f3745f43ac38b4438c9c7fb"