spring:
  application:
    name: chat_user-srv-eureka-client
  datasource:
    url: jdbc:postgresql://chat_user_database:5432/chat_user_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://chat_user_database:5432/chat_user_db
    password: 123
    user: postgres
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true
    baseline-version: 0
    baseline-description: "init"
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true