version: '3.8'
services:
  meeting_database:
    image: postgres:latest
    container_name: meeting_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: meeting_db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"
    volumes:
      - meeting-db-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - meeting-network

  meeting_application:
    container_name: meeting_application
    depends_on:
      - meeting_database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      DATABASE_URL: jdbc:postgresql://meeting_database:5432/meeting_db
      DATABASE_NAME: meeting_db
      DATABASE_PASSWORD: 123
      DATABASE_USER: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - meeting-network

networks:
  meeting-network:

volumes:
  meeting-db-data: