version: '3.8'
services:
  chat_database:
    image: postgres:latest
    container_name: chat_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: chat_db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5436:5432"
    volumes:
      - chat-db-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - chat-network

  chat_application:
    container_name: chat_application
    depends_on:
      - chat_database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9005:9005"
    environment:
      DATABASE_URL: jdbc:postgresql://chat_database:5432/chat_db
      DATABASE_NAME: chat_db
      DATABASE_PASSWORD: 123
      DATABASE_USER: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - chat-network

networks:
  chat-network:

volumes:
  chat-db-data: