server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #для корректной работы api-gateway
          lower-case-service-id: true #не чувствителен к регистру в названиях сервисов
      routes:
        - id: openapi
          uri: ${OPENAPI_URI:http://localhost:${server.port}}
          predicates:
            - Path=/v3/api-docs/{segment}
          filters:
            - SetPath=/{segment}/v3/api-docs
#            - RewritePath=/v3/api-docs/(?<segment>.*),/$\{segment}/v3/api-docs
        - id: chat
          uri: http://localhost:9005
          predicates:
            - Path=/api/v1/chat/**
            - Method=GET,POST
          filters:
            - name: CircuitBreaker
              args:
                name: chat-circuit-breaker
                fallbackUri: forward:/fallback/chatFail

        - id: dialog
          uri: http://localhost:9004
          predicates:
            - Path=/api/v1/dialog/**
            - Method=GET,POST
          filters:
            - name: CircuitBreaker
              args:
                name: dialog-circuit-breaker
                fallbackUri: forward:/fallback/dialogFail

        - id: event
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/event/**
            - Method=GET,POST,DELETE,PUT
          filters:
            - name: CircuitBreaker
              args:
                name: event-circuit-breaker
                fallbackUri: forward:/fallback/eventFail

        - id: meeting
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/meeting/**
            - Method=GET,POST
          filters:
            - name: CircuitBreaker
              args:
                name: meeting-circuit-breaker
                fallbackUri: forward:/fallback/meetingFail

        - id: user
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/user/**
            - Path=/api/v1/profile/**
            - Path=/api/v1/auth/**
            - Method=GET,POST,PUT
          filters:
            - name: CircuitBreaker
              args:
                name: user-circuit-breaker
                fallbackUri: forward:/fallback/userFail

  config:
    import: ${CONFIG_URI:optional:configserver:http://localhost:8888/}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true

springdoc:
  enable-native-support: true
  api-docs:
    groups:
      enabled: true
    enabled: true
  group-configs:
    - group: chat
      paths-to-match:
        - /api/v1/chat/**
      display-name: chat

    - group: dialog
      paths-to-match:
        - /api/v1/dialog/**
      display-name: dialog

    - group: event
      paths-to-match:
        - /api/v1/event/**
      display-name: event

    - group: meeting
      paths-to-match:
        - /api/v1/meeting/**
      display-name: meeting

    - group: user
      paths-to-match:
        - /api/v1/user/**
        - /api/v1/profile/**
        - /api/v1/auth/**
      display-name: user

  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - url: /v3/api-docs/chat
        name: chat

      - url: /v3/api-docs/dialog
        name: dialog

      - url: /v3/api-docs/event
        name: event

      - url: /v3/api-docs/meeting
        name: meeting

      - url: /v3/api-docs/user
        name: user
