server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #для корректной работы api-gateway
          lower-case-service-id: true #не чувствителен к регистру в названиях сервисов
  config:
    import: ${CONFIG_URI:optional:configserver:http://localhost:8888/}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true