version: '3.8'
services:
  event_database:
    image: postgres:latest
    container_name: event_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: event_db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5434:5432"
    volumes:
      - event-db-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - event-network

  event_application:
    container_name: event_application
    depends_on:
      - event_database
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:postgresql://event_database:5432/event_db
      DATABASE_NAME: event_db
      DATABASE_PASSWORD: 123
      DATABASE_USER: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - event-network

networks:
  event-network:

volumes:
  event-db-data: