spring:
  application:
    name: chat-srv-eureka-client
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5436/chat_db}
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5436/chat_db}
    password: 123
    user: postgres
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true
    baseline-version: 0
    baseline-description: "init"
server:
  port: 9005
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true