version: '3.8'
services:
  dialog_database:
    image: postgres:latest
    container_name: dialog_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dialog_db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5435:5432"
    volumes:
      - dialog-db-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - dialog-network

  dialog_application:
    container_name: dialog_application
    depends_on:
      - dialog_database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9004:9004"
    environment:
      DATABASE_URL: jdbc:postgresql://dialog_database:5432/dialog_db
      DATABASE_NAME: dialog_db
      DATABASE_PASSWORD: 123
      DATABASE_USER: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - dialog-network

networks:
  dialog-network:

volumes:
  dialog-db-data: