spring:
  application:
    name: dialog-srv-eureka-client
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435/dialog_db}
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435/dialog_db}
    password: 123
    user: postgres
    locations: classpath:db/migration
    baselineOnMigrate: true
    enabled: true
    baseline-version: 0
    baseline-description: "init"
server:
  port: 9004
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
resilience4j.circuitbreaker:
  instances:
    eren:
      registerHealthIndicator: true
      slidingWindowSize: 3 # оценка работоспособности сервиса на основе трех последних вызовов
      slow-call-duration-threshold: 4000 # если сервис работает дольше этого времени, то открыть схему
      permittedNumberOfCallsInHalfOpenState: 3 # столько максимум раз после ожидания будет вызван сервис для проверки
      minimumNumberOfCalls: 3
      waitDurationInOpenState: 50s